defaults:
  - GradDiff

handler: LoKU

args:
  learning_rate: 1e-4
  num_train_epochs: 5

method_args:
  gamma: 1.0
  alpha: 1.0
  ihl_alpha: 1.0
  retain_loss_type: NLL

  importance_file: null
  fila_eps: 1e-5
  fila_adapter_name: default
  fila_base_subdir: base_model
  run_fila_sanity_check: true
